-- =====================================================
-- Question 1
-- Business Question:
-- What is the total revenue generated by each store?
SELECT sum(amount) AS total_revenue, store.store_id FROM payment
INNER JOIN staff
ON payment.staff_id = staff.staff_id
INNER JOIN store 
ON staff.store_id = store.store_id
GROUP BY store_id;
-- =====================================================

-- =====================================================
-- Question 2
-- Business Question:
-- Which store generated the highest revenue?

SELECT store.store_id, SUM(amount) AS Highest_revenue FROM payment
INNER JOIN staff
ON payment.staff_id = staff.staff_id
INNER JOIN store
ON staff.store_id = store.store_id
GROUP BY store_id
ORDER BY Highest_revenue DESC
LIMIT 1;
 -- =====================================================

-- =====================================================
-- Question 3
-- Business Question:
-- What is the average payment amount?

SELECT AVG(amount) as avg_payment FROM payment;
-- =====================================================

-- =====================================================
-- Question 4
-- Business Question:
-- What are the top 10 highest payment transactions?

SELECT payment_id, customer_id, amount FROM payment
ORDER BY amount desc
LIMIT 10;
-- =====================================================

-- =====================================================
-- Question 5
-- Business Question:
-- How much revenue has each customer generated?
SELECT customer.customer_id, first_name, last_name, sum(amount) as total_revenue from customer
INNER JOIN payment
ON customer.customer_id = payment.customer_id
GROUP BY customer_id, first_name, last_name
ORDER BY sum(amount);