/*
====================================================================
Project : Sakila DVD Rental Business Analysis
File    : 03_revenue_analysis.sql
Author  : Lavanya Venukanti

Description:
This module analyzes revenue generated by stores, customers,
and payment transactions to evaluate business performance.

Skills Demonstrated:
- INNER JOIN
- GROUP BY
- Aggregate Functions
- ORDER BY
- LIMIT
====================================================================
*/
-- =====================================================
-- Question 1
-- Business Question:
-- What is the total revenue generated by each store?
SELECT sum(amount) AS total_revenue, store.store_id FROM payment
INNER JOIN staff
ON payment.staff_id = staff.staff_id
INNER JOIN store 
ON staff.store_id = store.store_id
GROUP BY store_id;
-- =====================================================

-- =====================================================
-- Question 2
-- Business Question:
-- Which store generated the highest revenue?

SELECT store.store_id, SUM(amount) AS highest_revenue FROM payment
INNER JOIN staff
ON payment.staff_id = staff.staff_id
INNER JOIN store
ON staff.store_id = store.store_id
GROUP BY store_id
ORDER BY highest_revenue DESC
LIMIT 1;
 -- =====================================================

-- =====================================================
-- Question 3
-- Business Question:
-- What is the average payment amount?

SELECT 
AVG(amount) AS average_payment_amount
FROM payment;
-- =====================================================

-- =====================================================
-- Question 4
-- Business Question:
-- What are the top 10 highest payment transactions?
SELECT
    payment_id,
    customer_id,
    amount
FROM payment
ORDER BY amount DESC
LIMIT 10;
-- =====================================================

-- =====================================================
-- Question 5
-- Business Question:
-- How much revenue has each customer generated?
SELECT customer.customer_id, first_name, last_name, sum(amount) as total_revenue from customer
INNER JOIN payment
ON customer.customer_id = payment.customer_id
GROUP BY customer_id, first_name, last_name
ORDER BY total_revenue DESC;
/*
====================================================================
End of Module 3 - Revenue Analysis
====================================================================
*/