-- =====================================================
-- Question 1
-- Business Question- Which customers generated the highest total revenue for the company?
-- Show the Top 10 customers along with their names and total revenue.

select customer.customer_id, first_name, last_name, sum(amount) as
total_amount
from customer
inner join payment
on customer.customer_id = payment.customer_id
group by customer_id, first_name, last_name
order by total_amount desc
limit 10;
-- =====================================================

-- =====================================================
-- Question 2
-- Business Question- How the Top 5 customers in each store based on total revenue.

with customer_revenue as
(select customer.customer_id, customer.store_id, sum(amount) as total_revenue
from payment
inner join customer
on payment.customer_id = customer.customer_id
group by customer_id,store_id),
store_rank as 
(select store_id, customer_id, total_revenue,
row_number() over
(partition by store_id
order by total_revenue desc)
as row_num
from customer_revenue)
select customer.store_id, customer.customer_id, first_name, last_name,
total_revenue, row_num
from store_rank
inner join customer
on store_rank.customer_id = customer.customer_id
where row_num <= 5;
-- =====================================================

-- =====================================================
-- Question 3
-- Business Question- Find customers whose total revenue is above the average customer revenue.

with customer_revenue as
(select customer_id, 
sum(amount) as total_revenue
from payment
group by customer_id)
average_revenue as
(select avg(total_revenue) as avg_revenue
from customer_revenue)
select customer_id, total_revenue
from customer_revenue
where total_revenue >
(select avg_revenue from average_revenue)
order by total_revenue desc;
-- =====================================================

-- =====================================================
-- Question 4
-- Business Question- For each month, calculate the total revenue and rank the months 
-- from highest to lowest revenue.

with monthly_revenue as
(select sum(amount) as total_revenue, monthname(payment_date) as month_name
from payment
group by month_name),
monthly_rank as
(select total_revenue, month_name,
row_number() over(order by total_revenue desc) as rank_row
from monthly_revenue)
select month_name, total_revenue, rank_row
from monthly_rank;
-- =====================================================

-- =====================================================
-- question 5
-- business question
-- Find the Top 10 most rented films.
select film.film_id, title, count(rental_id) as total_rentals
from film
inner join inventory
on film.film_id = inventory.film_id
inner join rental
on inventory.inventory_id = rental.inventory_id
group by film_id,title
order by total_rentals desc
limit 10;
-- =====================================================

-- =====================================================
-- question 6
-- business question
-- Find the Top 5 film categories by total revenue.
select name, sum(amount) as total_revenue
from payment
inner join rental
on payment.rental_id = rental.rental_id
inner join inventory
on rental.inventory_id = inventory.inventory_id
inner join film_category
on inventory.film_id = film_category.film_id
inner join category
on film_category.category_id = category.category_id
group by name
order by total_revenue desc
limit 5;
-- =====================================================

-- =====================================================
-- Question 7
-- Business Question- Show the Top 3 films within each film rating (G, PG, PG-13, R, etc.) 
-- based on rental count.

with film_rentals as
(select title, rating, count(rental_id) as total_rentals
from rental
inner join inventory
on rental.inventory_id = inventory.inventory_id
inner join film
on inventory.film_id = film.film_id
group by title, rating),
film_ranking as
(select title, rating, total_rentals,
row_number() over(partition by rating
order by total_rentals desc) as rank_row
from film_rentals)
select title, rating, total_rentals, rank_row
from film_ranking
where rank_row <= 3;
-- =====================================================

-- =====================================================
-- Question 8
-- Business Question- Calculate the total revenue generated by each store?
select store_id, sum(amount) as total_revenue
from payment
inner join customer
on payment.customer_id = customer.customer_id
group by store_id;
-- =====================================================

-- =====================================================
-- Question 9
-- Business Question- Which store has more customers?
select store_id, count(customer_id) as total_customers
from customer
group by store_id
order by total_customers desc
limit 1;
-- =====================================================

-- =====================================================
-- Question 10
-- Business Question: Find customers who have rented more films than the average customer?
with customer_rentals as
(select customer.customer_id, first_name, last_name, count(rental_id)
as total_rentals from rental
inner join customer
on rental.customer_id = customer.customer_id
group by customer_id, first_name, last_name),
average_rentals as
(select 
avg(total_rentals) as avg_rentals
from customer_rentals)
select customer_id, first_name, last_name, total_rentals
from customer_rentals
where total_rentals > 
(select avg_rentals from average_rentals);
-- =====================================================

-- =====================================================
-- Project Question 11
-- Business Question: Calculate the running monthly revenue.
with monthly_revenue as
(select monthname(payment_date) as month_name, month(payment_date) as month_number,
sum(amount) as total_revenue
from payment
group by month(payment_date),
         monthname(payment_date))
select month_number, month_name, total_revenue, sum(total_revenue)
over (order by month_number) as running_revenue
from monthly_revenue;
-- =====================================================

-- =====================================================
-- Project Question 12
-- Business Question: Compare each month's revenue with the previous month's revenue.
with monthly_revenue as
(select month(payment_date) as month_number,
monthname(payment_date) as month_name,
sum(amount) as total_revenue
from payment
group by month(payment_date), monthname(payment_date))
select month_number, month_name, total_revenue,
lag(total_revenue) over(order by month_number) as previous_month_revenue
from monthly_revenue;
-- =====================================================